# Generated by Django 3.1.7 on 2021-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('ward_no', models.IntegerField()),
                ('tole', models.CharField(max_length=50)),
                ('house_no', models.IntegerField()),
                ('address_type', models.CharField(max_length=50)),
            ],
        ),
    ]
